# fly.toml app configuration file generated for onlypizzas on 2023-08-18T10:41:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mvfacturacion"
primary_region = "mad"

[build]
  # Use the official Python buildpack
  buildpacks = ["heroku/python"]

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]