# Generated by Django 5.2.4 on 2025-07-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='num_pedido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='num_reparacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
