# Generated by Django 4.2.23 on 2025-07-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_factura_total_alter_factura_numero_factura_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocalizacionTrabajo',
            new_name='LocalizacionReparacion',
        ),
        migrations.RenameModel(
            old_name='Trabajo',
            new_name='Reparacion',
        ),
        migrations.RenameField(
            model_name='tarifa',
            old_name='nombre_trabajo',
            new_name='nombre_reparacion',
        ),
    ]
