# Generated by Django 4.2.23 on 2025-07-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_localizaciontrabajo_localizacionreparacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarifa',
            new_name='Trabajo',
        ),
        migrations.RenameModel(
            old_name='TarifaCliente',
            new_name='TrabajoCliente',
        ),
        migrations.RenameField(
            model_name='reparacion',
            old_name='tarifa',
            new_name='trabajo',
        ),
        migrations.RenameField(
            model_name='trabajocliente',
            old_name='tarifa',
            new_name='trabajo',
        ),
    ]
