# Generated by Django 4.2.23 on 2025-07-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_tarifa_trabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
