# Generated by Django 4.2.23 on 2025-07-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_trabajo_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proforma',
            name='total',
        ),
    ]
