# Generated by Django 4.2.23 on 2025-07-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_proforma_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacionreparacion',
            name='ascensor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='localizacionreparacion',
            name='localidad',
            field=models.CharField(max_length=50),
        ),
    ]
