# Generated by Django 4.2.23 on 2025-07-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_localizacionreparacion_ascensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacionreparacion',
            name='escalera',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='localizacionreparacion',
            name='ascensor',
            field=models.CharField(blank=True, default=1, max_length=20),
        ),
    ]
