# Generated by Django 4.2.23 on 2025-08-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_localizacionreparacion_escalera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
