# Generated by Django 4.2.23 on 2025-08-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_reparacion_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='facturas_pdfs/'),
        ),
    ]
