# Generated by Django 4.2.23 on 2025-08-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_factura_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='proformas_pdfs/'),
        ),
    ]
