# Generated by Django 4.2.23 on 2025-08-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_proforma_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Suministros', 'Suministros'), ('Materiales', 'Materiales'), ('Servicios', 'Servicios'), ('Impuestos', 'Impuestos'), ('Otros', 'Otros')], max_length=50)),
                ('estado', models.CharField(choices=[('pagada', 'pagada'), ('enviada', 'enviada'), ('pendiente de pago', 'pendiente de pago')], default='pendiente de pago', max_length=20)),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='gastos_archivos/')),
            ],
        ),
    ]
