# Generated by Django 4.2.23 on 2025-08-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='estado',
            field=models.CharField(choices=[('Pagada', 'Pagada'), ('Enviada', 'Enviada'), ('Pendiente de pago', 'Pendiente de pago')], default='pendiente de pago', max_length=20),
        ),
    ]
