# Generated by Django 4.2.23 on 2025-08-05 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_gasto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReparacionFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_reparacion/')),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='api.reparacion')),
            ],
        ),
    ]
