# Generated by Django 4.2.23 on 2025-08-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_reparacionfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='especial',
            field=models.BooleanField(default=False),
        ),
    ]
