# Generated by Django 4.2.23 on 2025-08-05 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_trabajo_especial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trabajo'),
        ),
    ]
