# Generated by Django 4.2.23 on 2025-08-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_reparacion_trabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='trabajo',
        ),
        migrations.CreateModel(
            name='TrabajosReparaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_reparaciones', to='api.reparacion')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trabajo')),
            ],
            options={
                'unique_together': {('reparacion', 'trabajo')},
            },
        ),
    ]
